/**
 * Service landing pages. Each entry renders /services/<slug> with its own
 * title, meta description, H1, FAQ schema and a dedicated enquiry form.
 * `slug` must match a Service slug in the CRM (Settings → Services).
 * Prices are indicative "starting from" figures — confirm before launch.
 */
module.exports = [
  {
    slug: 'website-development',
    name: 'Website Development',
    short: 'Fast, SEO-ready websites built to turn visitors into enquiries.',
    illustration: 'webdev',
    metaTitle: 'Website Development Company in India | Fast, SEO-Ready Sites',
    metaDescription: 'Custom website development by Digital Guru — fast, mobile-first, SEO-ready business websites with lead forms, WhatsApp and CRM integration.',
    kicker: 'Website Development',
    h1: 'Websites that load fast, rank well and bring in enquiries.',
    intro: 'Your website is your hardest-working salesperson. We design and develop custom, mobile-first websites with clean code, strong on-page SEO and conversion paths built in — so every visit has a clear next step.',
    startingPrice: '₹14,999',
    deliverables: [
      { t: 'Custom design, no templates', d: 'Layouts designed around your brand, offer and customer journey — not a recycled theme.' },
      { t: 'Mobile-first & lightning fast', d: 'Optimised images, clean code and Core Web Vitals in mind so pages load quickly on 4G.' },
      { t: 'On-page SEO foundations', d: 'Meta tags, schema markup, sitemap, clean URLs and heading structure set up from day one.' },
      { t: 'Lead capture built in', d: 'Enquiry forms, click-to-call, WhatsApp buttons and thank-you pages that track conversions.' },
      { t: 'Easy to update', d: 'Edit content yourself or let us handle it — with training and documentation included.' },
      { t: 'Secure hosting setup', d: 'SSL, backups, uptime monitoring and a smooth launch on your domain.' },
    ],
    process: [
      { t: 'Discover', d: 'We map your goals, audience, competitors and the pages you need.' },
      { t: 'Design', d: 'Wireframes and visual design for key pages, refined with your feedback.' },
      { t: 'Develop', d: 'Responsive build, integrations, speed and SEO optimisation.' },
      { t: 'Launch & grow', d: 'QA on real devices, go-live, analytics setup and post-launch support.' },
    ],
    outcomes: ['Business websites & corporate sites', 'Landing pages for ad campaigns', 'Service businesses that need enquiries', 'Redesigns of slow or outdated sites'],
    faqs: [
      { q: 'How long does it take to build a website?', a: 'A typical business website takes 2–4 weeks from kickoff to launch, depending on the number of pages and how quickly content and feedback come in. Landing pages can go live in under a week.' },
      { q: 'Will my website be mobile-friendly and SEO-ready?', a: 'Yes. Every site is designed mobile-first and ships with technical SEO foundations — titles, meta descriptions, schema markup, XML sitemap, fast loading and clean URLs.' },
      { q: 'Can I update the website myself?', a: 'Yes. We can build on an easy-to-edit CMS and train your team, or you can choose a monthly maintenance plan and we will handle updates for you.' },
      { q: 'Do you provide hosting and domain?', a: 'We can set up hosting, SSL and your domain, or deploy to your existing hosting account — whichever you prefer.' },
    ],
    related: ['website-design', 'seo', 'ecommerce-development'],
  },
  {
    slug: 'website-design',
    name: 'Website Design',
    short: 'Distinctive UI/UX that makes your brand look as good as it is.',
    illustration: 'branding',
    metaTitle: 'Website Design Agency | UI/UX Design for Brands | Digital Guru',
    metaDescription: 'Creative website design and UI/UX by Digital Guru. Distinctive, conversion-focused layouts, landing pages and design systems for growing brands in India.',
    kicker: 'Website Design',
    h1: 'Design that makes people stop scrolling — and start enquiring.',
    intro: 'Good design is not decoration. We craft interfaces that make your offer instantly clear, build trust in seconds and guide visitors to act — with a visual identity that is unmistakably yours.',
    startingPrice: '₹9,999',
    deliverables: [
      { t: 'UX research & wireframes', d: 'User journeys and page structure planned before a single pixel is designed.' },
      { t: 'Custom visual design', d: 'Typography, colour, illustration and layout tailored to your brand.' },
      { t: 'Conversion-focused layouts', d: 'Clear hierarchy, strong CTAs and trust signals where they matter.' },
      { t: 'Responsive design for every screen', d: 'Desktop, tablet and mobile designs — not just a shrunk desktop.' },
      { t: 'Design system', d: 'Reusable components, colours and type styles for consistency as you grow.' },
      { t: 'Developer-ready handoff', d: 'Organised Figma files with specs, assets and interaction notes.' },
    ],
    process: [
      { t: 'Brief', d: 'Brand, audience, goals and what success looks like.' },
      { t: 'Wireframe', d: 'Low-fidelity layouts to agree on structure and content.' },
      { t: 'Visual design', d: 'High-fidelity designs with two rounds of revisions.' },
      { t: 'Handoff', d: 'Design system and assets handed over — or built by our dev team.' },
    ],
    outcomes: ['Brands launching a new website', 'Businesses whose site looks dated', 'Startups needing a design system', 'Landing pages for campaigns'],
    faqs: [
      { q: 'What is the difference between website design and development?', a: 'Design covers how your website looks and works for users — layout, visuals and user experience. Development turns those designs into a working, fast website. We offer both, separately or together.' },
      { q: 'How many design revisions are included?', a: 'Our standard packages include two rounds of revisions on the key page designs. Additional rounds can be added if needed.' },
      { q: 'Do you design in Figma?', a: 'Yes. You receive organised Figma files with components and styles, so any developer can build from them.' },
    ],
    related: ['website-development', 'branding', 'ecommerce-development'],
  },
  {
    slug: 'seo',
    name: 'SEO',
    short: 'Rank for the searches your customers are already making.',
    illustration: 'seo',
    metaTitle: 'SEO Services in India | Local & Technical SEO | Digital Guru',
    metaDescription: 'Result-focused SEO services — technical SEO, local SEO, keyword research, on-page optimisation and content that ranks. Grow organic traffic and leads.',
    kicker: 'Search Engine Optimisation',
    h1: 'Get found on Google by customers who are ready to buy.',
    intro: 'SEO compounds. We fix the technical issues holding your site back, target the keywords that bring buyers rather than browsers, and build content and authority that keeps paying off month after month.',
    startingPrice: '₹9,999/mo',
    deliverables: [
      { t: 'Technical SEO audit', d: 'Crawl errors, site speed, indexing, schema and Core Web Vitals — fixed and monitored.' },
      { t: 'Keyword & competitor research', d: 'High-intent keywords mapped to the right pages, with realistic difficulty.' },
      { t: 'On-page optimisation', d: 'Titles, meta descriptions, headings, internal links and content improvements.' },
      { t: 'Local SEO', d: 'Google Business Profile optimisation, local citations and location pages.' },
      { t: 'Content that ranks', d: 'Blog posts and service pages written for search intent and conversions.' },
      { t: 'Monthly reporting', d: 'Rankings, organic traffic and leads — in plain language, every month.' },
    ],
    process: [
      { t: 'Audit', d: 'Full technical and content audit with a prioritised action plan.' },
      { t: 'Fix foundations', d: 'Resolve technical issues and optimise existing pages first.' },
      { t: 'Create & build', d: 'New content, local signals and quality backlinks.' },
      { t: 'Measure & refine', d: 'Track rankings and leads; double down on what works.' },
    ],
    outcomes: ['Local businesses competing in their city', 'Service companies wanting steady leads', 'E-commerce stores growing organic sales', 'Sites that lost traffic after an update'],
    faqs: [
      { q: 'How long does SEO take to show results?', a: 'Most sites see early movement in 6–12 weeks after technical fixes and on-page work. Competitive keywords usually take 4–6 months of consistent effort. We report progress monthly so you can see the trend.' },
      { q: 'Do you guarantee first-page rankings?', a: 'No honest agency can guarantee rankings because Google controls its results. We commit to transparent work, measurable improvements in visibility and traffic, and a clear monthly report.' },
      { q: 'Do you offer local SEO for my city?', a: 'Yes. Local SEO includes Google Business Profile optimisation, local keywords, location pages, reviews strategy and citation building.' },
      { q: 'Is SEO better than Google Ads?', a: 'They work best together. Ads bring leads immediately; SEO builds a long-term, lower-cost lead channel. Many clients start with ads while SEO grows.' },
    ],
    related: ['google-ads', 'website-development', 'performance-marketing'],
  },
  {
    slug: 'google-ads',
    name: 'Google Ads',
    short: 'Search, Performance Max and YouTube campaigns tuned for leads.',
    illustration: 'ads',
    metaTitle: 'Google Ads Management & PPC Services | Digital Guru',
    metaDescription: 'Google Ads management — Search, Performance Max, Display and YouTube campaigns with conversion tracking and weekly optimisation for lower cost per lead.',
    kicker: 'Google Ads Management',
    h1: 'Google Ads that bring leads, not just clicks.',
    intro: 'We build tightly structured campaigns around high-intent keywords, write ads that earn the click, and send traffic to landing pages built to convert — with proper conversion tracking so every rupee is accountable.',
    startingPrice: '₹7,999/mo',
    deliverables: [
      { t: 'Account & keyword strategy', d: 'Intent-based keyword research, match types and negative keyword lists.' },
      { t: 'Campaign build', d: 'Search, Performance Max, Display and YouTube — structured for control.' },
      { t: 'Ad copy & extensions', d: 'Compelling responsive ads with sitelinks, callouts and call assets.' },
      { t: 'Conversion tracking', d: 'Forms, calls and WhatsApp clicks tracked with GA4 and Google Ads.' },
      { t: 'Landing page optimisation', d: 'Fast, focused pages that match the ad and lift conversion rate.' },
      { t: 'Weekly optimisation', d: 'Bids, search terms, budgets and A/B tests reviewed every week.' },
    ],
    process: [
      { t: 'Audit or setup', d: 'Review your account (or build one) and install tracking.' },
      { t: 'Launch', d: 'Go live with focused campaigns and controlled budgets.' },
      { t: 'Optimise', d: 'Cut wasted spend, scale winning keywords and ads.' },
      { t: 'Scale', d: 'Expand to new campaigns once cost per lead is stable.' },
    ],
    outcomes: ['Businesses that need leads this month', 'Accounts with high cost per lead', 'Local services competing on search', 'E-commerce shopping campaigns'],
    faqs: [
      { q: 'How much should I spend on Google Ads?', a: 'It depends on your industry and location. Many local service businesses start with ₹15,000–₹50,000 per month in ad spend. We recommend a budget after reviewing keyword costs for your market.' },
      { q: 'Is the management fee separate from ad spend?', a: 'Yes. Ad spend is paid directly to Google from your account. Our management fee covers strategy, setup, optimisation and reporting.' },
      { q: 'Will I own my Google Ads account?', a: 'Always. Campaigns run in your own account and you keep full access and history, even if you stop working with us.' },
      { q: 'How do you track leads from ads?', a: 'We set up conversion tracking for form submissions, calls and WhatsApp clicks, and pass UTM data into your CRM so you can see which campaigns bring booked customers.' },
    ],
    related: ['performance-marketing', 'meta-ads', 'lead-generation'],
  },
  {
    slug: 'meta-ads',
    name: 'Meta Ads',
    short: 'Facebook & Instagram ads with creatives that stop the scroll.',
    illustration: 'ads',
    metaTitle: 'Meta Ads Agency | Facebook & Instagram Ads | Digital Guru',
    metaDescription: 'Facebook and Instagram ads that generate leads and sales: audience strategy, scroll-stopping creatives, Meta Lead Ads and Conversions API setup.',
    kicker: 'Facebook & Instagram Ads',
    h1: 'Scroll-stopping Meta Ads that fill your pipeline.',
    intro: 'Great Meta campaigns are 70% creative. We pair sharp audience strategy with thumb-stopping reels, carousels and static ads — then track results properly with the Meta Pixel and Conversions API.',
    startingPrice: '₹7,999/mo',
    deliverables: [
      { t: 'Audience strategy', d: 'Interest, lookalike and retargeting audiences built from your data.' },
      { t: 'Creative production', d: 'Reels, carousels and static ads designed for each placement.' },
      { t: 'Lead Ads & landing pages', d: 'Instant forms or landing pages — whichever gives better-quality leads.' },
      { t: 'Pixel & Conversions API', d: 'Accurate tracking so Meta optimises for real leads and sales.' },
      { t: 'Creative testing', d: 'Structured A/B tests on hooks, formats and offers every month.' },
      { t: 'Transparent reporting', d: 'Cost per lead, lead quality and ROAS — not vanity metrics.' },
    ],
    process: [
      { t: 'Strategy', d: 'Offer, audience and funnel planned before spending.' },
      { t: 'Create', d: 'Ad creatives and copy in multiple variations.' },
      { t: 'Launch & test', d: 'Controlled tests to find winning audiences and ads.' },
      { t: 'Scale', d: 'Increase budget on winners while protecting cost per lead.' },
    ],
    outcomes: ['Brands selling to consumers', 'Real estate, education & healthcare leads', 'Local businesses & events', 'E-commerce product launches'],
    faqs: [
      { q: 'Should I run Facebook or Instagram ads?', a: 'Usually both. Meta Ads run across Facebook and Instagram from one account, and the algorithm shifts budget to whichever placement performs best for your goal.' },
      { q: 'Are Meta Lead Ads good quality?', a: 'They can be, with the right setup. We add qualifying questions, use higher-intent form types and sync leads to your CRM instantly so your team can follow up fast.' },
      { q: 'Do you create the ad creatives?', a: 'Yes. Creative production — designs, reels and copy — is part of our Meta Ads service.' },
    ],
    related: ['social-media-marketing', 'google-ads', 'lead-generation'],
  },
  {
    slug: 'social-media-marketing',
    name: 'Social Media Marketing',
    short: 'Content calendars, reels and community that build real demand.',
    illustration: 'social',
    metaTitle: 'Social Media Marketing Agency in India | Digital Guru',
    metaDescription: 'Social media marketing that builds brand and demand — content strategy, reels, carousels, community management and analytics for Instagram and LinkedIn.',
    kicker: 'Social Media Marketing',
    h1: 'Social media that builds a brand people remember.',
    intro: 'Posting is easy; being remembered is hard. We plan content around what your audience actually cares about, produce reels and carousels with a consistent visual identity, and turn followers into enquiries.',
    startingPrice: '₹11,999/mo',
    deliverables: [
      { t: 'Content strategy', d: 'Pillars, formats and a monthly calendar aligned with your goals.' },
      { t: 'Reels & video', d: 'Short-form scripts, editing and trending audio for reach.' },
      { t: 'Carousels & posts', d: 'On-brand designs that educate, entertain and convert.' },
      { t: 'Community management', d: 'Replies to comments and DMs, with enquiries routed to your team.' },
      { t: 'Profile optimisation', d: 'Bio, highlights, links and CTAs set up to drive action.' },
      { t: 'Monthly analytics', d: 'Reach, engagement, followers and enquiries — explained simply.' },
    ],
    process: [
      { t: 'Audit', d: 'Review your profiles and competitors.' },
      { t: 'Plan', d: 'Content pillars and a monthly calendar for approval.' },
      { t: 'Create & post', d: 'Produce, schedule and publish consistently.' },
      { t: 'Engage & improve', d: 'Community management and data-driven tweaks.' },
    ],
    outcomes: ['Brands building awareness', 'Founders growing on LinkedIn', 'Restaurants, retail & lifestyle', 'Businesses with inconsistent posting'],
    faqs: [
      { q: 'How many posts per month do you create?', a: 'Packages typically include 12–20 posts per month including reels, carousels and stories. We recommend a mix based on your goals and platform.' },
      { q: 'Which platforms do you manage?', a: 'Instagram, Facebook, LinkedIn and YouTube Shorts. We focus on the platforms where your customers actually spend time.' },
      { q: 'Do you shoot videos?', a: 'We script and edit reels, and can arrange shoots in select cities. We can also work with footage your team records on a phone.' },
    ],
    related: ['meta-ads', 'branding', 'lead-generation'],
  },
  {
    slug: 'lead-generation',
    name: 'Lead Generation',
    short: 'Full-funnel systems that deliver qualified enquiries daily.',
    illustration: 'leadgen',
    metaTitle: 'Lead Generation Services for B2B & B2C | Digital Guru',
    metaDescription: 'End-to-end lead generation — ads, landing pages, WhatsApp and CRM follow-up systems that deliver qualified leads daily. Pay for results you can measure.',
    kicker: 'Lead Generation',
    h1: 'A steady flow of qualified leads — every single day.',
    intro: 'Leads are not a campaign; they are a system. We connect ads, landing pages, WhatsApp and a CRM with fast follow-up, so enquiries do not just arrive — they get answered, qualified and converted.',
    startingPrice: '₹14,999/mo',
    deliverables: [
      { t: 'Funnel strategy', d: 'Offer, audience and channel mix designed for your sales cycle.' },
      { t: 'High-converting landing pages', d: 'Focused pages with forms, WhatsApp and call tracking.' },
      { t: 'Multi-channel campaigns', d: 'Google, Meta and LinkedIn ads working together.' },
      { t: 'CRM & instant alerts', d: 'Every lead captured with its source, so no enquiry slips through.' },
      { t: 'Lead qualification', d: 'Qualifying questions and scoring so sales focuses on hot leads.' },
      { t: 'Cost-per-lead reporting', d: 'See exactly which campaigns bring booked customers.' },
    ],
    process: [
      { t: 'Map the funnel', d: 'Define ideal customer, offer and conversion points.' },
      { t: 'Build', d: 'Landing pages, tracking and CRM connected end-to-end.' },
      { t: 'Launch', d: 'Campaigns go live with daily monitoring.' },
      { t: 'Optimise', d: 'Improve lead quality and lower cost per lead.' },
    ],
    outcomes: ['Real estate & home services', 'Education & coaching', 'B2B services & SaaS', 'Clinics & healthcare'],
    faqs: [
      { q: 'How quickly will I start getting leads?', a: 'Once campaigns and landing pages are live — usually within 7–10 days of kickoff — most clients begin receiving enquiries in the first week of ads running.' },
      { q: 'Do you guarantee a number of leads?', a: 'We share realistic projections based on your budget and market, and report cost per lead transparently. Results depend on offer, budget and follow-up speed, so we do not make blanket guarantees.' },
      { q: 'Can leads come directly into my CRM or WhatsApp?', a: 'Yes. Leads can flow into a CRM with instant alerts, and your team can respond on WhatsApp in one click.' },
    ],
    related: ['google-ads', 'meta-ads', 'marketing-automation'],
  },
  {
    slug: 'branding',
    name: 'Branding',
    short: 'Logos, identity systems and messaging with personality.',
    illustration: 'branding',
    metaTitle: 'Branding Agency | Logo Design & Brand Identity | Digital Guru',
    metaDescription: 'Brand identity design by Digital Guru — logo design, colour palettes, typography, brand guidelines and messaging that make your business memorable and trusted.',
    kicker: 'Branding & Identity',
    h1: 'A brand identity people recognise at a glance.',
    intro: 'Your brand is the feeling people get before they read a word. We create logos, colour systems, typography and a voice that make you look established, trustworthy and unmistakably you.',
    startingPrice: '₹12,999',
    deliverables: [
      { t: 'Brand strategy', d: 'Positioning, audience and personality defined in a short workshop.' },
      { t: 'Logo design', d: 'Primary logo, secondary marks and icon versions for every use.' },
      { t: 'Colour & typography', d: 'A distinctive palette and type system that works on screen and print.' },
      { t: 'Brand guidelines', d: 'A clear guide so everyone uses your brand consistently.' },
      { t: 'Messaging & tagline', d: 'Taglines and key messages in a consistent tone of voice.' },
      { t: 'Brand collateral', d: 'Business cards, social templates, letterheads and presentations.' },
    ],
    process: [
      { t: 'Discover', d: 'Workshop on vision, audience and competitors.' },
      { t: 'Explore', d: 'Two to three creative directions presented.' },
      { t: 'Refine', d: 'Develop the chosen direction into a full identity.' },
      { t: 'Deliver', d: 'Guidelines, files and templates ready to use.' },
    ],
    outcomes: ['New businesses & startups', 'Rebrands and refreshes', 'Product launches', 'Personal brands'],
    faqs: [
      { q: 'How many logo concepts will I get?', a: 'We present two to three distinct creative directions, then refine the one you choose into a complete identity.' },
      { q: 'Which files do I receive?', a: 'All logo versions in SVG, PNG and PDF, colour codes, fonts, and a brand guidelines PDF.' },
      { q: 'How long does branding take?', a: 'Most brand identity projects take 3–5 weeks from workshop to final files.' },
    ],
    related: ['website-design', 'social-media-marketing', 'website-development'],
  },
  {
    slug: 'ecommerce-development',
    name: 'E-commerce Development',
    short: 'Online stores with smooth checkout, payments and shipping.',
    illustration: 'ecommerce',
    metaTitle: 'E-commerce Website Development | Shopify | Digital Guru',
    metaDescription: 'E-commerce website development — Shopify, WooCommerce and custom stores with UPI/Razorpay payments, shipping integration and product SEO.',
    kicker: 'E-commerce Development',
    h1: 'Online stores that make buying feel effortless.',
    intro: 'We build e-commerce stores that load fast, look premium and make checkout painless — with UPI and card payments, shipping integrations and the product SEO you need to get discovered.',
    startingPrice: '₹29,999',
    deliverables: [
      { t: 'Store design', d: 'Premium product, collection and checkout pages designed to sell.' },
      { t: 'Platform setup', d: 'Shopify, WooCommerce or a custom build — chosen for your needs.' },
      { t: 'Payments & shipping', d: 'Razorpay, UPI, cards, COD and courier integrations.' },
      { t: 'Product SEO', d: 'Structured data, optimised product pages and fast category pages.' },
      { t: 'Marketing integrations', d: 'Meta Pixel, GA4, Google Merchant Center and WhatsApp.' },
      { t: 'Training & support', d: 'Learn to manage products, orders and discounts yourself.' },
    ],
    process: [
      { t: 'Plan', d: 'Catalogue, platform, payments and shipping decided.' },
      { t: 'Design', d: 'Store design focused on product discovery and checkout.' },
      { t: 'Build', d: 'Development, integrations and product upload.' },
      { t: 'Launch', d: 'Test orders, analytics and go-live support.' },
    ],
    outcomes: ['D2C brands', 'Retailers going online', 'Manufacturers selling direct', 'Stores migrating platforms'],
    faqs: [
      { q: 'Shopify or WooCommerce — which is better?', a: 'Shopify is quicker to launch and easier to manage; WooCommerce offers more flexibility and lower recurring costs. We recommend a platform after understanding your catalogue, budget and growth plans.' },
      { q: 'Can you integrate UPI and COD?', a: 'Yes. We integrate Razorpay, Cashfree or PhonePe for UPI, cards and net-banking, plus cash-on-delivery with courier partners.' },
      { q: 'Do you upload products?', a: 'Yes. Product upload is included up to an agreed number of products, and bulk uploads can be handled via CSV.' },
    ],
    related: ['website-development', 'performance-marketing', 'seo'],
  },
  {
    slug: 'performance-marketing',
    name: 'Performance Marketing',
    short: 'ROI-first campaigns across Google, Meta and beyond.',
    illustration: 'performance',
    metaTitle: 'Performance Marketing Agency in India | Digital Guru',
    metaDescription: 'Performance marketing focused on ROAS and cost per acquisition — Google, Meta and YouTube ads, conversion tracking, landing pages and data-driven scaling.',
    kicker: 'Performance Marketing',
    h1: 'Marketing measured in revenue, not impressions.',
    intro: 'Performance marketing means every rupee has a job. We run full-funnel campaigns across Google, Meta and YouTube, track conversions end-to-end, and scale only what brings profitable customers.',
    startingPrice: '₹19,999/mo',
    deliverables: [
      { t: 'Full-funnel media plan', d: 'Prospecting, retargeting and retention mapped to budget.' },
      { t: 'Cross-channel campaigns', d: 'Google, Meta, YouTube and LinkedIn managed together.' },
      { t: 'Tracking & attribution', d: 'GA4, server-side events and UTM discipline for clean data.' },
      { t: 'Creative testing engine', d: 'Constant testing of hooks, formats and offers.' },
      { t: 'Landing page CRO', d: 'A/B tests that lift conversion rates over time.' },
      { t: 'Revenue dashboards', d: 'ROAS, CPA and pipeline value in one view.' },
    ],
    process: [
      { t: 'Baseline', d: 'Audit tracking and past performance.' },
      { t: 'Plan', d: 'Channel mix, budget split and targets.' },
      { t: 'Execute', d: 'Launch, test and optimise weekly.' },
      { t: 'Scale', d: 'Grow spend on profitable channels.' },
    ],
    outcomes: ['E-commerce & D2C brands', 'Lead-gen businesses with sales teams', 'Apps & SaaS', 'Brands spending ₹1L+/month on ads'],
    faqs: [
      { q: 'What is performance marketing?', a: 'Performance marketing is advertising where success is measured by specific actions — leads, sales or sign-ups — rather than impressions. Budgets are optimised continuously towards the lowest cost per result.' },
      { q: 'What ROAS can I expect?', a: 'It varies widely by industry, margins and price point. We set targets after an audit and report ROAS and cost per acquisition every week.' },
      { q: 'Do you work on a commission of ad spend?', a: 'We offer both fixed monthly fees and percentage-of-spend models for larger budgets. We will recommend what fits your scale.' },
    ],
    related: ['google-ads', 'meta-ads', 'lead-generation'],
  },
  {
    slug: 'marketing-automation',
    name: 'Marketing Automation',
    short: 'CRM, WhatsApp and email flows that follow up for you.',
    illustration: 'automation',
    metaTitle: 'Marketing Automation: CRM, WhatsApp & Email | Digital Guru',
    metaDescription: 'Marketing automation that follows up for you — CRM setup, WhatsApp and email automation, lead nurturing and reminders so no lead goes cold. By Digital Guru.',
    kicker: 'Marketing Automation',
    h1: 'Follow up with every lead — automatically.',
    intro: 'Most leads are lost to slow follow-up. We set up CRM workflows, WhatsApp and email sequences and smart reminders so every enquiry gets a fast, personal response — even when your team is busy.',
    startingPrice: '₹14,999',
    deliverables: [
      { t: 'CRM setup', d: 'Pipelines, lead stages and fields configured for your sales process.' },
      { t: 'WhatsApp automation', d: 'Instant replies and follow-up templates via the WhatsApp Business API.' },
      { t: 'Email nurturing', d: 'Welcome, nurture and re-engagement sequences.' },
      { t: 'Lead routing', d: 'Assign leads to the right person automatically.' },
      { t: 'Reminders & tasks', d: 'Never miss a follow-up with automated reminders.' },
      { t: 'Integrations', d: 'Connect forms, ads, Google Sheets and your tools.' },
    ],
    process: [
      { t: 'Map', d: 'Document your current lead journey and gaps.' },
      { t: 'Design', d: 'Plan workflows, messages and triggers.' },
      { t: 'Build', d: 'Configure CRM, automations and integrations.' },
      { t: 'Train', d: 'Team training and ongoing optimisation.' },
    ],
    outcomes: ['Sales teams handling many enquiries', 'Businesses losing leads to slow replies', 'Coaching & education', 'Real estate & services'],
    faqs: [
      { q: 'Do I need the WhatsApp Business API?', a: 'For automated WhatsApp messages at scale, yes. We help you apply for and set up the API through an official provider.' },
      { q: 'Which CRM do you work with?', a: 'We can set up a custom CRM like the one powering this website, or configure popular tools such as Zoho, HubSpot or LeadSquared.' },
      { q: 'Can automation feel personal?', a: 'Yes. Messages use the lead’s name, service and context, and hand over to a human the moment the lead replies.' },
    ],
    related: ['lead-generation', 'performance-marketing', 'website-development'],
  },
];
